server:
  port: 9090
  
management:
  security:
    enabled: false
  
spring: 
  profile: dev
  application: 
    name:  spring-config-9090
  cloud: 
    config: 
      server: 
        git:
          uri: https://github.com/hsh7244/learn-spring-cloud.git
          force-pull: true